#!/bin/sh
# postinst script
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        if which glib-compile-schemas >/dev/null 2>&1
        then
            glib-compile-schemas /usr/share/glib-2.0/schemas
        fi
        if which systemctl >/dev/null 2>&1
        then
            systemctl enable mythicos-update-automation-cleanup.service || true
            systemctl disable mythicos-update-automation-upgrade.service || true
            systemctl disable mythicos-update-automation-autoremove.service || true
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    triggered)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
